### ISSUE TITLE
chore: set up basic formatting and linting

### ISSUE THREAD

**Issue by arjunr00** [UCLA-Creative-Labs/sunshine#16]
- [ ] For formatting, use [Prettier](https://prettier.io/) with a [config file](https://prettier.io/docs/en/configuration.html).
- [x] For linting, use [ESLint](https://eslint.org/).
- [x] Use commit/push hooks and/or Actions to enforce these rules.

**Comment by BryanPan342** [comment]
+1 for eslint

i think we can have a github actions that checkouts the branch and runs yarn lint?

I think we should write our own `.eslintrc.js` file which i don't mind taking a stab at
